[package]
name = "fastsync-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
ciborium.workspace = true
fastsync-core = { path = "../fastsync-core" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
